// Смена/Z-отчёт на уровне мок-api: операция задним числом и отмена старой операции во время смены
import { createJiti } from 'jiti';
const root = process.env.ROOT || '/Users/arsen/WebstormProjects/booking-platform';
const jiti = createJiti(import.meta.url, { alias: { '@docs': root + '/docs', '@messages': root + '/messages', '@': root + '/src' }, jsx: true });
const db = await jiti.import(root + '/src/mock/db.ts');
await db.bootDb();
const fin = await jiti.import(root + '/src/api/finance.ts');
const S = () => db.useDb.getState();
let pass = 0, fail = 0;
const check = (n, ok, info = '') => { ok ? pass++ : fail++; console.log(ok ? 'PASS' : 'FAIL', n, info); };
const biz = 'biz_atam';
const accs = await fin.listAccountsWithBalance(biz);
const cash = accs.find((a) => a.kind === 'cash');
const item = (await fin.listItems(biz)).find((i) => i.kind === 'income' || i.group === 'income') ?? (await fin.listItems(biz))[0];
console.log('cash', cash.name, cash.balance, 'item', item.name);
let v = await fin.openCashShift(biz, cash.id, cash.balance);
check('открытие без расхождения — без поправки', (v.shift.adjustmentOperationIds ?? []).length === 0);
const y = new Date(Date.now() - 86400000).toISOString().slice(0, 10) + 'T12:00';
const now = new Date(Date.now() + 4 * 3600000).toISOString().slice(0, 16);
await fin.recordOperation(biz, { locationId: cash.locationId, accountId: cash.id, itemId: item.id, kind: 'income', amount: 5000, date: now.slice(0, 10) + 'T' + v.shift.openedAt.slice(11), method: 'cash', partyType: 'none' });
await fin.recordOperation(biz, { locationId: cash.locationId, accountId: cash.id, itemId: item.id, kind: 'income', amount: 3000, date: y, method: 'cash', partyType: 'none', comment: 'задним числом' });
const shifts = await fin.listCashShifts(biz, cash.id);
const open = shifts.find((x) => x.shift.status === 'open');
check('открытая смена: Z «должно быть» = остаток по учёту', open.report.expected === open.expectedNow, `Z ${open.report.expected} / учёт ${open.expectedNow}`);
v = await fin.closeCashShift(biz, open.shift.id, open.expectedNow);
check('закрытие: Z «должно быть» = «по учёту» при закрытии', v.report.expected === v.shift.expectedAtClose, `Z ${v.report.expected} / при закрытии ${v.shift.expectedAtClose}`);
check('закрытие: расхождение 0', v.discrepancy === 0, String(v.discrepancy));
console.log(`ИТОГ ${pass}/${pass + fail}`);
process.exit(0);
