import { start, stop, open, go, text, shot, db, settle } from './lib.mjs';
const log = (...a) => console.log(...a);
await start();
const { page } = await open('client', '/book?staff=st_nuri_ani&slot=2026-09-25T15%3A00', { device: 'phone' });
const nBefore = (await db(page)).core.bookings.length;
await page.getByText('Маникюр с покрытием гель-лаком').click();
await page.getByRole('button', { name: 'Продолжить' }).click(); await page.waitForTimeout(1500);
log('--- after service\n' + await text(page));
await page.getByText('гель-лак', { exact: true }).first().click();
await page.getByRole('button', { name: 'Продолжить' }).click(); await page.waitForTimeout(1500);
log('--- confirm\n' + await text(page));
await page.getByText('Ребёнок', { exact: true }).click(); await page.waitForTimeout(300);
const nameInput = page.getByPlaceholder('Как зовут');
if (await nameInput.count()) await nameInput.fill('Мариам');
await shot(page, 'c2-02-confirm', true);
await page.getByRole('button', { name: 'Подтвердить запись' }).click();
await page.waitForTimeout(3000);
log('--- after confirm URL', page.url());
log(await page.locator('[role=status], [data-sonner-toast], [role=alert]').allInnerTexts().catch(()=>[]));
await settle(page);
log(await text(page));
const d = await db(page);
log('bookings', nBefore, '->', d.core.bookings.length);
const nb = d.core.bookings.slice(-3).filter(b => b.staffId === 'st_nuri_ani');
log(JSON.stringify(nb));
log('shade', JSON.stringify(d.areas.client.bookingShade).slice(0,400));
await shot(page, 'c2-03-bookings');
log('ERR', page.errors);
await stop();
