import { start, stop, open, go, text, shot, db, settle } from './lib.mjs';
const log = (...a) => console.log(...a);
await start();
// fresh context: book again via a slot then wait for redirect
const { page, context } = await open('client', '/masters/st_nuri_ani', { device: 'phone' });
log('--- master slots (fresh ctx)\n', (await text(page)).match(/Ближайшие свободные окна[\s\S]*?Сообщить/)?.[0]);
await page.getByRole('button', { name: /Сегодня, / }).first().or(page.getByRole('link', { name: /Сегодня, / }).first()).click();
await settle(page);
log('URL', page.url());
await page.getByText('Маникюр с покрытием гель-лаком').click();
await page.getByRole('button', { name: 'Продолжить' }).click(); await page.waitForTimeout(800);
await page.getByText('гель-лак', { exact: true }).first().click();
await page.getByRole('button', { name: 'Продолжить' }).click(); await page.waitForTimeout(800);
await page.getByText('Ребёнок', { exact: true }).click(); await page.waitForTimeout(300);
await page.getByPlaceholder('Как зовут').fill('Мариам');
const t0 = Date.now();
await page.getByRole('button', { name: 'Подтвердить запись' }).click();
await page.waitForURL(/\/bookings$/, { timeout: 60000 }).then(()=>log('redirect after ms', Date.now()-t0)).catch(()=>log('NO REDIRECT in 60s', page.url()));
await settle(page);
log('--- bookings\n' + await text(page));
const d = await db(page);
const nb = d.core.bookings.filter(b => b.createdBy === 'client' && b.createdAt >= '2026-09-25');
log('new', JSON.stringify(nb.map(b=>[b.id,b.start,b.status])));
const id = nb.at(-1).id;
await go(page, '/bookings/' + id);
log('--- detail\n' + await text(page));
await page.reload(); await settle(page);
log('--- detail after reload\n' + await text(page));
await shot(page, 'c3-detail', true);
await go(page, '/masters/st_nuri_ani');
log('--- master slots after booking\n', (await text(page)).match(/Ближайшие свободные окна[\s\S]*?Сообщить/)?.[0]);
await go(page, '/places/biz_nuri');
log('--- place\n', (await text(page)).match(/Мои записи здесь[\s\S]{0,600}/)?.[0]);
await go(page, '/');
log('--- home\n', (await text(page)).match(/Ближайшие записи[\s\S]*?Мои мастера/)?.[0]);
// owner journal
await go(page, '/biz/journal?demo=owner&sphere=nails');
const jt = await text(page);
log('--- journal has Ани? 15:00', /15:00/.test(jt), jt.slice(0, 1500));
await shot(page, 'c3-journal-owner');
log('ERR', page.errors);
await stop();
