import { start, stop, open, go, text, shot, db, settle } from './lib.mjs';
const log = (...a) => console.log(...a);
const toast = async (page) => (await page.locator('[role=status], [role=alert]').allInnerTexts().catch(()=>[])).filter(Boolean);
await start();
const { page } = await open('owner', '/biz/journal', { device: 'desktop' });
const cols = page.locator('[data-f="F-01-024"]');
log('cols', await cols.count());
const tl = page.locator('[data-f*="F-01-018"]').getByText('16:00', { exact: true }).first();
await tl.scrollIntoViewIfNeeded(); await page.waitForTimeout(300);
const col = await cols.nth(0).boundingBox();
const tick = await tl.boundingBox();
log('elementAt', await page.evaluate(([x,y]) => { const e = document.elementFromPoint(x,y); return e?.tagName + ' ' + (e?.getAttribute('data-f')||'') + ' ' + (e?.className||'').toString().slice(0,60); }, [col.x + col.width/2, tick.y + tick.height/2 + 2]));
log('col', col, 'tick', tick);
await page.mouse.click(col.x + col.width/2, tick.y + tick.height/2 + 2);
await page.waitForTimeout(2000);
const dlg = page.locator('[role=dialog]').last();
log('--- new window\n' + (await dlg.innerText()).slice(0, 2500));
await shot(page, 'j2-new-window');
const n0 = (await db(page)).core.bookings.length;
await dlg.getByText('Маникюр классический').first().click(); await page.waitForTimeout(700);
await dlg.locator('input[type=tel]').first().fill('55443322'); await page.waitForTimeout(500);
const nm = dlg.getByPlaceholder('Имя').first(); if (await nm.count()) await nm.fill('Перепроверка Журнал');
const btns = await dlg.getByRole('button').allInnerTexts(); log('buttons', btns.filter(b=>/Сохран|Создав/.test(b)));
await dlg.getByRole('button', { name: /Создавать записи|Сохранить/ }).last().click(); await page.waitForTimeout(2500);
log('toast', await toast(page), 'dialog open?', await page.locator('[role=dialog]').count());
const extra = page.locator('[role=dialog], [role=alertdialog]'); if (await extra.count()) log('extra dialog', (await extra.last().innerText()).slice(0,300));
const gridTxt = await page.locator('[data-f*="F-01-018"]').innerText();
log('grid has new (no reload)', /Перепроверка/.test(gridTxt), gridTxt.match(/16:00[^\n]*\n[^\n]*\n[^\n]*/)?.[0]);
const d1 = await db(page); const nb = d1.core.bookings.slice(n0);
log('new bookings', JSON.stringify(nb.map(b=>[b.staffId,b.start,b.durationMin,b.status,b.clientId,b.total,b.source])));
await page.reload(); await settle(page);
log('grid has new (after reload)', /Перепроверка/.test(await page.locator('[data-f*="F-01-018"]').innerText()));
const cl = d1.core.clients.find(c=>c.phone?.endsWith('55443322')); log('client created in base', JSON.stringify(cl && [cl.id, cl.name, cl.businessId]));
log('ERR', page.errors.slice(0,4));
await stop();
