import { start, stop, open, go, text, shot, db, settle } from './lib.mjs';
const log = (...a) => console.log(...a);
await start();
const { page } = await open('guest', '/b/nuri-nail-studio/book', { device: 'phone' });
await page.getByText('Маникюр классический', { exact: true }).first().click(); await page.waitForTimeout(500);
await page.getByRole('button', { name: /Продолжить/ }).click(); await page.waitForTimeout(1500);
await page.getByText('Ани Саргсян').first().click(); await page.waitForTimeout(1000);
if (await page.getByRole('button', { name: 'Понятно' }).count()) await page.getByRole('button', { name: 'Понятно' }).click();
await page.waitForTimeout(500);
await page.getByRole('button', { name: /Продолжить/ }).click(); await page.waitForTimeout(2000);
log('--- step3\n' + (await text(page)).slice(0, 2500));
await shot(page, 'o3-step3', true);
await page.getByRole('button', { name: '15:30' }).click(); await page.waitForTimeout(500);
await page.getByRole('button', { name: /Продолжить/ }).click(); await page.waitForTimeout(1500);
log('--- step4\n' + (await text(page)).slice(0, 2500));
const inputs = await page.locator('input, textarea').evaluateAll(els => els.map(e => [e.type, e.name, e.placeholder, e.getAttribute('aria-label')].join('|')));
log('inputs', inputs);
await shot(page, 'o3-step4', true);
log('ERR', page.errors.slice(0,3));
await stop();
