import { start, stop, open, go, text, shot, db, settle } from './lib.mjs';
const log = (...a) => console.log(...a);
await start();
const { page } = await open('owner', '/biz/schedule', { device: 'desktop' });
const row = () => page.locator('tr', { hasText: 'Ани Саргсян' }).first();
await row().locator('td, button', { hasText: 'чт, 24 сентября' }).last().click(); await page.waitForTimeout(1000);
const dlg = page.locator('[role=dialog]').last();
await dlg.locator('select').filter({ has: page.locator('option', { hasText: 'Нерабочий день' }) }).selectOption({ label: 'Нерабочий день' }); await page.waitForTimeout(400);
const del = () => page.locator('[role=dialog]').last().getByRole('button', { name: 'Удалить', exact: true });
await del().click(); await page.waitForTimeout(1200);
if (await page.locator('[role=dialog]').count()) await del().click();
const undo = page.getByRole('button', { name: 'Отменить', exact: true });
await undo.waitFor({ timeout: 8000 });
log('row after delete', (await row().innerText()).split('\n').slice(-1), 'db', JSON.stringify((await db(page)).core.schedules.filter(s=>s.staffId==='st_nuri_ani'&&s.workplace==='salon').map(s=>s.overrides['2026-09-24'])));
await undo.click(); await page.waitForTimeout(2500);
log('row after undo', (await row().innerText()).split('\n').slice(-1), 'db', JSON.stringify((await db(page)).core.schedules.filter(s=>s.staffId==='st_nuri_ani'&&s.workplace==='salon').map(s=>s.overrides['2026-09-24'])));
await page.reload(); await settle(page);
log('row after reload', (await row().innerText()).split('\n').slice(-1));
log('ERR', page.errors.slice(0,3));
await stop();
