const { page } = await L.newPage(browser, { persona: 'owner' });
state.m = page;
await L.go(page, '/biz/services/new'); await page.waitForTimeout(1500);
await page.getByLabel('Название · Русский').fill('QA Маникюр 0930');
await page.locator('#svc-f-category').click(); await page.getByRole('option', { name: 'Маникюр' }).click();
await page.locator('#svc-f-duration').click(); await page.getByRole('option', { name: '1 ч', exact: true }).click();
await page.getByRole('combobox', { name: 'Минуты' }).click(); await page.getByRole('option', { name: '30 мин' }).click();
await page.getByText('Цена «от–до»').click(); await page.waitForTimeout(300);
await page.locator('input#svc-f-price').fill('8000'); await page.locator('input#svc-f-price-max').fill('12000');
await page.getByText('Ани Саргсян', { exact: true }).click();
await page.getByLabel(/Напомнить клиенту через/).fill('21');
await page.getByRole('button', { name: 'Сохранить' }).click(); await page.waitForTimeout(2000);
log('toast:', await page.locator('[data-sonner-toast]').allInnerTexts());
state.svcId = await page.evaluate(() => { const v = JSON.parse(localStorage.getItem('bp-mock-db:core:services')); const arr = Array.isArray(v) ? v : (v.state ?? v).items ?? Object.values(v); const s = JSON.stringify(v); const i = s.indexOf('QA Маникюр 0930'); return s.slice(i, i + 400).match(/"id":"(sv_[^"]+)"/)?.[1]; });
log('svc', state.svcId);
await L.go(page, '/biz/notifications/inbox'); await page.waitForTimeout(1000);
await page.getByRole('tab', { name: /Новости сервиса/ }).click(); await page.waitForTimeout(1000);
await page.getByRole('button', { name: /Чат с поддержкой/ }).first().click(); await page.waitForTimeout(800);
const d = page.locator('[role=dialog]').last();
await d.locator('textarea').fill('QA-0930 тест обращения из кабинета');
await d.getByRole('button', { name: /Отправить/ }).click(); await page.waitForTimeout(1500);
log('toast', await page.locator('[data-sonner-toast]').allInnerTexts());
await L.as(page, 'platform');
await L.go(page, '/platform/support'); await page.waitForTimeout(1200);
const t = await page.innerText('main');
log('support in platform:', t.includes('QA-0930 тест обращения'), t.match(/[^\n]*\n[^\n]*QA-0930[^\n]*\n[^\n]*\n[^\n]*/)?.[0]);
await L.shot(page, 'platform', 's01-support-new-ticket');
await L.go(page, '/platform/moderation'); await page.waitForTimeout(1200);
const mt = await page.innerText('main');
log('QA service in moderation queue:', mt.includes('QA Маникюр 0930'), '| pending count', mt.match(/На проверке\n(\d+)/)?.[1]);
