const { page } = await L.newPage(browser, { persona: 'owner', empty: true });
state.e = page;
await L.go(page, '/biz/services'); await page.waitForTimeout(2000);
log('EMPTY:', (await page.innerText('main')).replace(/\n\s*\n+/g, '\n').slice(0, 500));
await L.shot(page, 'services', 'e01-empty-catalog');
await L.go(page, '/biz/services/templates'); await page.waitForTimeout(1500);
log('TPL:', (await page.innerText('main')).replace(/\n\s*\n+/g, '\n').slice(0, 300));
await page.getByRole('checkbox', { name: 'Классический маникюр' }).check({ force: true });
await page.getByRole('checkbox', { name: 'Снятие покрытия' }).check({ force: true });
log('sel', (await page.innerText('main')).match(/Выбрано: \d+/)?.[0]);
await page.getByRole('button', { name: 'Добавить выбранные' }).click(); await page.waitForTimeout(2000);
log('url', page.url(), await page.locator('[data-sonner-toast]').allInnerTexts());
await L.go(page, '/biz/services'); await page.waitForTimeout(1500);
log('AFTER:', (await page.innerText('main')).replace(/\n\s*\n+/g, '\n').slice(0, 700));
await L.shot(page, 'services', 'e02-after-templates');
log('ERR', page.errors);
