import { chromium } from '@playwright/test';
import { acquireBrowserSlot } from '../../../../scripts/pw-slots.mjs';
const release = await acquireBrowserSlot();
const browser = await chromium.launch();
const ctx = await browser.newContext();
const page = await ctx.newPage();
const warnings = [];
page.on('console', (msg) => { if (msg.type() === 'warning' || msg.type() === 'error') warnings.push(msg.text()); });
await page.goto('http://localhost:3710/biz/loyalty/card-types/new?demo=owner', { waitUntil: 'networkidle' });
await page.fill('input[placeholder="Например, «Карта постоянного клиента»"]', 'Замер персистентности g2-1');
await page.waitForTimeout(300);
const saveBtn = page.getByRole('button', { name: /Сохранить/ }).first();
await saveBtn.click({ timeout: 8000 }).catch((e)=>console.log('save click err', e.message));
await page.waitForTimeout(1500);
console.log('warnings after save:', JSON.stringify(warnings));
await page.goto('http://localhost:3710/biz/loyalty/card-types?demo=owner', { waitUntil: 'networkidle' });
await page.waitForTimeout(500);
const text = await page.textContent('body');
console.log('New type visible after nav?', text.includes('Замер персистентности g2-1'));
await page.reload({ waitUntil: 'networkidle' });
await page.waitForTimeout(500);
const text2 = await page.textContent('body');
console.log('New type visible after RELOAD?', text2.includes('Замер персистентности g2-1'));
await browser.close();
await release();
