import { acquireBrowserSlot } from '../../../../scripts/pw-slots.mjs';
import { chromium } from '@playwright/test';
const release = await acquireBrowserSlot();
const b = await chromium.launch();
const p = await b.newPage();
const errs = [];
p.on('pageerror', (e) => errs.push('pageerror: ' + e.message));
p.on('console', (m) => { if (m.type() === 'error') errs.push('console: ' + m.text()); });
await p.setViewportSize({ width: 1440, height: 900 });
await p.goto('http://localhost:3710/biz/journal?demo=owner&sphere=nails&lang=ru&theme=light');
await p.waitForTimeout(1800);
await p.getByText('Педикюр классический').first().click();
await p.waitForTimeout(700);
await p.getByRole('tab', { name: 'Лояльность' }).click();
await p.waitForTimeout(900);
await p.getByRole('button', { name: 'Разделить оплату' }).click();
await p.waitForTimeout(500);
const input = p.locator('input[type=text], input[type=number]').last();
await input.fill('1000');
await p.getByRole('button', { name: 'Применить' }).click();
await p.waitForTimeout(700);
await p.screenshot({ path: 'qa/shots/loyalty-g1-2/bonus-split2/1-after-apply.png', fullPage: true });
await p.getByRole('tab', { name: 'Оплата' }).click();
await p.waitForTimeout(600);
await p.screenshot({ path: 'qa/shots/loyalty-g1-2/bonus-split2/2-payment-tab.png', fullPage: true });
console.log('ERRORS:', JSON.stringify(errs));
await b.close();
release();
