import { acquireBrowserSlot } from '../../../../scripts/pw-slots.mjs';
import { chromium } from '@playwright/test';
const release = await acquireBrowserSlot();
const b = await chromium.launch();
const p = await b.newPage();
const errs = [];
p.on('pageerror', (e) => errs.push('pageerror: ' + e.message));
p.on('console', (m) => { if (m.type() === 'error') errs.push(m.type()+': ' + m.text()); });
await p.setViewportSize({ width: 1440, height: 900 });
await p.goto('http://localhost:3710/biz/loyalty?demo=owner&sphere=nails&lang=ru&theme=light');
await p.waitForTimeout(1500);
await p.getByRole('button', { name: 'Настроить' }).nth(0).click();
await p.waitForTimeout(900);
console.log('URL_AFTER_CARDS_CONFIGURE:', p.url());
await p.goBack();
await p.waitForTimeout(700);
await p.getByRole('button', { name: 'Настроить' }).nth(1).click();
await p.waitForTimeout(900);
console.log('URL_AFTER_CERTS_CONFIGURE:', p.url());
await p.goBack();
await p.waitForTimeout(700);
await p.getByRole('button', { name: 'Помогите мне настроить' }).click();
await p.waitForTimeout(900);
await p.screenshot({ path: 'qa/shots/loyalty-g1-2/hub-nav/1-help-clicked.png', fullPage: true });
console.log('URL_AFTER_HELP:', p.url());
console.log('ERRORS:', JSON.stringify(errs));
await b.close();
release();
