import { acquireBrowserSlot } from '../../../../scripts/pw-slots.mjs';
import { chromium } from '@playwright/test';
const release = await acquireBrowserSlot();
const b = await chromium.launch();
const p = await b.newPage();
const errs = [];
p.on('pageerror', (e) => errs.push('pageerror: ' + e.message));
p.on('console', (m) => errs.push(m.type()+': ' + m.text()));
p.on('framenavigated', (f) => console.log('NAV_EVENT:', f.url()));
await p.setViewportSize({ width: 1440, height: 900 });
await p.goto('http://localhost:3710/biz/loyalty?demo=owner&sphere=nails&lang=ru&theme=light');
await p.waitForTimeout(1200);
await p.getByRole('link', { name: 'Настроить' }).first().click();
await p.waitForTimeout(2500);
console.log('URL_AFTER:', p.url());
await p.screenshot({ path: 'qa/shots/loyalty-g1-2/hub-nav4/after.png', fullPage: true });
console.log('CONSOLE_ALL:', JSON.stringify(errs.slice(-15)));
await b.close();
release();
