import { start, stop, open, as, text, shot, db, toasts, pick } from './lib.mjs';
await start();
const { page } = await open('owner', `/biz/clients`, { device: 'desktop' });
await page.getByText('Неявщики', { exact: false }).first().click(); await page.waitForTimeout(1500);
console.log('list count', (await text(page)).match(/\d+–\d+ из \d+/)?.[0]);
await page.getByRole('button', { name: /Действия/ }).first().click(); await page.waitForTimeout(600);
console.log('MENU head', (await page.locator('[role=menu]').last().innerText().catch(()=>'')).split('\n').slice(0,2).join(' / '));
await shot(page, 'c11-menu-with-filter');
await page.getByText('Добавить в категорию').click(); await page.waitForTimeout(800);
const dlg = page.locator('[role=dialog]').last();
console.log('CAT', (await dlg.innerText()).replace(/\n+/g,' | ').slice(0,100));
const inp = dlg.getByRole('combobox'); await inp.click(); await inp.fill('Проверка C3'); await page.waitForTimeout(500);
const opts = await page.getByRole('option').allInnerTexts(); console.log('opts', opts);
if (opts.length) await page.getByRole('option').filter({hasText:'Проверка C3'}).first().click().catch(()=>page.keyboard.press('Enter')); else await page.keyboard.press('Enter');
await page.waitForTimeout(500);
await dlg.getByRole('button', { name: 'Добавить' }).last().click(); await page.waitForTimeout(3000); 
const d = await db(page);
const tagged = d.core.clients.filter(c=>(c.tags||[]).includes('Проверка C3'));
const ns = new Set(d.core.bookings.filter(b=>b.status==='no_show'&&!b.deletedAt).map(b=>b.clientId));
console.log('tagged', tagged.length, 'of which no-show', tagged.filter(c=>ns.has(c.id)).length);
await stop();
