import { start, stop, open, as, reload, text, shot, db, toasts, pick } from './lib.mjs';
await start();
const { page } = await open('owner', '/biz/clients/summary', { device: 'desktop' });
const rev0 = (await text(page)).match(/Выручка\n([^\n]+)/)?.[1];
await as(page, 'owner', '/biz/clients/cl_001');
await page.getByRole('button', { name: 'Добавить визит' }).first().click(); await page.waitForTimeout(800);
const sh = page.locator('[role=dialog]').last();
await pick(page, sh.getByRole('combobox').nth(0), 'Ани Саргсян');
await pick(page, sh.getByRole('combobox').nth(1), 'Маникюр аппаратный');
const inputs = await sh.locator('input').evaluateAll(els=>els.filter(e=>e.type!=='file' && e.type!=='hidden').map(e=>`${e.type}|${e.placeholder}|${e.getAttribute('aria-label')}|${e.value}`)); console.log('inputs', inputs);
await shot(page, 'c3-sheet-service-picked');
const money = sh.locator('input[inputmode=numeric], input[inputmode=decimal]'); console.log('money inputs', await money.count());
await money.first().fill('12345'); await page.waitForTimeout(300);
console.log('paid hint', (await sh.innerText()).match(/По умолчанию[^\n]+/)?.[0]);
const ids0 = new Set((await db(page)).core.bookings.map(b=>b.id));
await sh.getByRole('button', { name: 'Сохранить визит' }).click(); await page.waitForTimeout(2500);
const d = await db(page); const nb = d.core.bookings.filter(b=>!ids0.has(b.id)); console.log('new', JSON.stringify(nb.map(b=>[b.start,b.status,b.total,b.services.map(s=>[s.serviceId,s.price])])), JSON.stringify(nb[0] && d.areas.clients.manualVisitPayments[nb[0].id]));
await as(page, 'owner', '/biz/clients/summary');
console.log('revenue before', rev0, 'after', (await text(page)).match(/Выручка\n([^\n]+)/)?.[1]);
await as(page, 'owner', '/biz/clients/cl_001');
const t = await text(page); console.log('card', t.slice(t.indexOf('Продано'), t.indexOf('Продано')+120).replace(/\n/g,' | '));
await stop();
