import { start, stop, open, as, reload, text, shot, db, toasts } from './lib.mjs';
await start();
const DATE='2026-10-13';
const { page } = await open('owner', `/biz/journal?new=1&staff=st_nuri_ani&start=13:00&date=${DATE}`, { device: 'desktop' });
const win = page.locator('[role=dialog]').last();
await win.getByRole('button', { name: /Маникюр классический\s*5 000/ }).first().click(); await page.waitForTimeout(600);
await win.getByLabel(/Скидка/).first().fill('10'); await page.waitForTimeout(600);
await win.getByPlaceholder('91 234 567').fill('77001199'); await win.getByPlaceholder('Имя').fill('Скидка Тест'); await page.waitForTimeout(300);
await win.getByRole('button', { name: 'Записать' }).last().click(); await page.waitForTimeout(2500); console.log('toasts', await toasts(page));
const find = async () => { const d = await db(page); return { b: d.core.bookings.filter(b=>b.staffId==='st_nuri_ani' && b.start===`${DATE}T13:00`), ex: d.areas.journal.extras, cl: d.core.clients.filter(c=>c.phone==='+37477001199') }; };
let r = await find(); console.log('db now', JSON.stringify(r.b), JSON.stringify(r.cl.map(c=>[c.id,c.name])));
await page.waitForTimeout(3000); r = await find(); console.log('db +3s', JSON.stringify(r.b.map(b=>[b.id,b.total,b.services.map(s=>[s.price,s.discountPct,s.total])])), r.b[0] && JSON.stringify(r.ex[r.b[0].id]));
await as(page, 'owner', `/biz/journal?date=${DATE}`);
r = await find(); console.log('after nav', JSON.stringify(r.b.map(b=>[b.id,b.total,b.status])));
await page.locator('[data-testid="booking-block"]', { hasText: '13:00' }).first().click(); await page.waitForTimeout(1500);
const w2 = page.locator('[role=dialog]').last(); const t=await w2.innerText(); const k=t.indexOf('К оплате'); console.log('reopen', JSON.stringify(t.slice(k,k+25)));
const k2 = t.indexOf('Маникюр классический'); console.log('svc line', JSON.stringify(t.slice(k2, k2+80)));
await shot(page, 'j8-reopen');
await w2.getByRole('button', { name: 'Клиент подтвердил' }).click(); await page.waitForTimeout(300);
await w2.getByRole('button', { name: 'Сохранить изменения' }).click(); await page.waitForTimeout(1500); console.log('toasts', await toasts(page));
await as(page, 'owner', `/biz/journal?date=${DATE}`);
r = await find(); console.log('status after nav', JSON.stringify(r.b.map(b=>[b.status,b.total])));
await stop();
