import { start, stop, open, as, reload, text, shot, db, toasts, wizardToDetails } from './lib.mjs';
await start();
const { page } = await open('owner', `/biz/online/settings`, { device: 'desktop' });
const S = page.getByRole('switch');
await S.nth(4).click(); await S.nth(5).click(); await page.waitForTimeout(300); await S.nth(6).click(); await page.waitForTimeout(300);
await page.getByRole('button', { name: 'Сохранить' }).nth(1).click(); await page.waitForTimeout(1200);
await page.getByPlaceholder('Название поля').fill('Номер машины');
await page.locator('label').filter({ hasText: /^Обязательное$/ }).last().click().catch(()=>{});
await page.getByRole('button', { name: 'Добавить поле' }).click(); await page.waitForTimeout(1500);
let d = await db(page); console.log('cfg', JSON.stringify({ e: d.areas.online.clientFields.biz_nuri.emailRequired, ln: d.areas.online.clientFields.biz_nuri.lastNameRequired, cf: d.areas.online.clientFields.biz_nuri.customFields }));
await as(page, 'guest', '/b/nuri-nail-studio/book');
console.log('reached details', await wizardToDetails(page, { log: true }));
let t = await text(page); console.log('DETAILS', t.slice(0,1200).replace(/\n/g,' | '));
const inputs = await page.locator('main input, main textarea').evaluateAll(els=>els.map(e=>`${e.type}|${e.placeholder}|${e.name}|req=${e.required||e.getAttribute('aria-required')}`)); console.log(inputs);
await shot(page, 'o3-details', true);
await page.getByPlaceholder('Введите имя').fill('Поля Тест'); await page.getByPlaceholder('91 234 567').fill('91234571');
await page.getByText('Записываясь, вы соглашаетесь').click().catch(()=>{});
await page.getByRole('button', { name: /Записаться/ }).click(); await page.waitForTimeout(1200);
t = await text(page); console.log('AFTER SUBMIT (missing fields)', t.slice(0,900).replace(/\n/g,' | '));
d = await db(page); console.log('bookings by phone', JSON.stringify(d.core.bookings.filter(b=>{ const c = d.core.clients.find(x=>x.id===b.clientId); return c?.phone==='+37491234571'; }).map(b=>[b.id,b.start,b.status])));
await shot(page, 'o3-after-submit', true);
await stop();
