import { start, stop, open, as, reload, text, shot, db, toasts } from './lib.mjs';
await start();
const { page } = await open('master', '/biz/schedule/calendar', { device: 'desktop' });
let d = await db(page);
const today = '2026-09-25';
const ani = d.core.bookings.filter(b => b.staffId==='st_nuri_ani' && b.start.startsWith(today) && !b.deletedAt).sort((a,b)=>a.start.localeCompare(b.start));
console.log('now', new Date().toString());
console.log('ani today', JSON.stringify(ani.map(b=>[b.id,b.start,b.durationMin,b.status,b.clientId, b.appUserId])));
const t = await text(page); const i = t.indexOf('Закончил раньше'); console.log('CARD', t.slice(Math.max(0,i-600), i+200));
await as(page, 'client', '/book?staff=st_nuri_ani&service=sv_nuri_classic');
console.log('client slots before', (await text(page)).match(/\d\d:\d\d/g));
await as(page, 'master', '/biz/schedule/calendar');
await page.getByRole('button', { name: 'Закончил раньше' }).first().click(); await page.waitForTimeout(2000);
console.log('toasts', await toasts(page));
d = await db(page);
const first = ani.find(b => !['cancelled_by_client','cancelled_by_master','no_show'].includes(b.status));
const nb = d.core.bookings.find(b=>b.id===first.id); console.log('first booking now', nb.id, nb.start, nb.durationMin, nb.status);
await shot(page, 's3-finish-early');
await as(page, 'client', '/book?staff=st_nuri_ani&service=sv_nuri_classic');
console.log('client slots after', (await text(page)).match(/\d\d:\d\d/g));
// delay
await as(page, 'master', '/biz/schedule/calendar');
await page.getByRole('button', { name: 'Задерживаюсь' }).first().click(); await page.waitForTimeout(2000);
console.log('toasts', await toasts(page));
d = await db(page); console.log('delay', JSON.stringify(d.areas.schedule.delayNotices));
const n = Object.values(d.areas.schedule.delayNotices)[0]; const nx = d.core.bookings.find(b=>b.id===n?.nextBookingId);
console.log('next', JSON.stringify(nx && {id:nx.id, start:nx.start, client:nx.clientId, app:nx.appUserId}));
const cl = d.core.clients.find(c=>c.id===nx?.clientId); console.log('client', JSON.stringify(cl && {name:cl.name, app:cl.appUserId, phone: cl.phone}));
console.log('client notif kinds', JSON.stringify(d.areas.client.notifications.map(x=>x.kind)));
await stop();
